version: "3"
services:
        web:
                build: .
                container_name: app1
                volumes:
                        - ./src/:/var/www/html
                ports:
                        - "8080:80"
                networks:
                        - backend
                env_file:
                        - ./env/desarrollo.env




        db:
                image: mysql:latest
                container_name: mysql1
                #environment:
                        #MYSQL_ROOT_PASSWORD: mora
                        #MYSQL_DATABASE: ejercicio
                        #MYSQL_USER: mora
                        #MYSQL_PASSWORD: mora
                
                volumes:
                        - ./dump:/docker-entrypoint-initdb.d
                env_file:
                        - ./env/desarrollo.env
                networks:
                        backend:
                                ipv4_address: 10.25.0.3
        mongodb:
                image: mongo:latest
                container_name: mongo1
                #environment:
                        #MONGO_INITDB_ROOT_USERNAME: mora
                        #MONGO_INITDB_ROOT_PASSWORD: mora
                        #MONGO_INITDB_DATABASE: mongo
                
                networks:
                        backend:
                                ipv4_address: 10.25.0.2
                env_file:
                        - ./env/desarrollo.env
networks:
     backend:
         external: false
         #name: custom_backend
         driver: bridge
         ipam:
           config:
                 - subnet: 10.25.0.0/5
                   #gateway: 10.25.0.1
                           





