version: "3"
services:
        db:
                image: mysql:latest
                container_name: mysql1
                #environment:
                        #MYSQL_ROOT_PASSWORD: mora2
                        #MYSQL_DATABASE: ejercicio2
                        #MYSQL_USER: mora2
                        #MYSQL_PASSWORD: mora2
                volumes:
                        - volumenmysql:/var/lib/mysql/
                networks:
                        frontend:
                                ipv4_address: 10.25.0.6
                env_file:
                        - ./env/produccion.env
        mongodb:
                image: mongo:latest
                container_name: mongo1
                #environment:
                        #MONGO_INITDB_ROOT_USERNAME: mora2
                        #MONGO_INITDB_ROOT_PASSWORD: mora2
                        #MONGO_INITDB_DATABASE: mongo2
                volumes:
                        - volumenmongo:/data/db/
                networks:
                        frontend:
                                ipv4_address: 10.25.0.5
                env_file:
                        - ./env/produccion.env
        web:
                build: .
                container_name: app2
                volumes:
                        - ./src/:/var/www/html/
                ports:
                        - "8090:80"
                networks:
                        - frontend
                env_file:
                        - ./env/produccion.env
volumes:
        volumenmysql:
        volumenmongo:
networks:
     frontend:
          external: false
          #name: prueba_backend
          driver: bridge
          ipam:
            config:
                 - subnet: 10.25.0.0/6
                   #gateway: 10.25.0.4

